make usbromservice sync BIOS folder from usb also. update copyright header. fixes #1269

diff --git a/scriptmodules/supplementary/usbromservice/01_retropie_copyroms b/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
--- a/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
+++ b/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
@@ -1,7 +1,12 @@
 #!/bin/bash -ue
-# Sync ROMS from external drive
-# Christian Bryn <chr.bryn@gmail.com> 2013
-# Florian Mueller <contact@petrockblock.com> 2015
+# This file is part of The RetroPie Project
+# 
+# The RetroPie Project is the legal property of its developers, whose names are
+# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
+# 
+# See the LICENSE.md file at the top-level directory of this distribution and 
+# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
+#
 
 ## config / defaults
 user="USERTOBECHOSEN"
@@ -9,10 +14,8 @@ user="USERTOBECHOSEN"
 home="$(eval echo ~$user)"
 rootdir="/opt/retropie"
 retropie_path="$home/RetroPie"
-retropie_path_roms="$retropie_path/roms"
 
 usb_path="$UM_MOUNTPOINT/retropie"
-usb_path_roms="$usb_path/roms"
 usb_path_from_rp="$usb_path/configs/from_retropie"
 usb_path_to_rp="$usb_path/configs/to_retropie"
 
@@ -46,17 +49,19 @@ if [[ ! -d "$usb_path" ]]; then
 fi
 
 # make folders for syncing
-mkdir -p "$usb_path_roms" "$usb_path_from_rp" "$usb_path_to_rp"
+mkdir -p "$usb_path/"{roms,BIOS} "$usb_path_from_rp" "$usb_path_to_rp"
 
 # mirror romdir structure to external drive
-log info "Attempting to create directory structure for ROMS in '$usb_path_roms' ..."
+log info "Attempting to create directory structure for ROMS in '$usb_path/roms' ..."
 # fetch list of romdirs from current installation and mirror onto external drive
-find "$retropie_path"/roms -mindepth 1 -maxdepth 1 -type d -printf "$usb_path_roms/%f\n" | xargs mkdir -p 2>/dev/null || true
+find "$retropie_path/roms" -mindepth 1 -maxdepth 1 -type d -printf "$usb_path/roms/%f\n" | xargs mkdir -p 2>/dev/null || true
 
-log info "Syncing roms ..."
-# copy ROMs from USB stick to local SD card
-rsync -rtu --exclude '._*' --max-delete=-1 "$usb_path_roms/" "$retropie_path_roms/" >/dev/null 2>&1 || log err "rsync failed to sync ROMS, returned error code $?"
-chown -R $user:$user "$retropie_path_roms"
+# copy ROMs/BIOS from USB stick to local SD card
+for dir in roms BIOS; do
+    log info "Syncing $dir ..."
+    rsync -rtu --exclude '._*' --max-delete=-1 "$usb_path/$dir" "$retropie_path/" >/dev/null 2>&1 || log err "rsync failed to sync $dir, returned error code $?"
+    chown -R $user:$user "$retropie_path/$dir"
+done
 
 log info "Syncing configs ..."
 # copy configs to usb
